---
- name: install nginx
  yum:
    name: nginx-1.10.2
    state: present
    update_cache: true
- name: enable http port on the firewall
  firewalld:
    service: http
    permanent: true
    zone: public
    state: enabled