---
- name: check which version is installed
  command: "{{ant_home}}/bin/ant -version | awk '/^Apache Ant/ {print $4}'"
  changed_when: false
  failed_when: false
  check_mode: no
  register: ant_current_version
  tags: ['ant']

- name: check if the new version should be installed or not
  set_fact:
    install_ant: "{{ ant_current_version.rc > 0 or (ant_current_version.stdout | version_compare(ant_version, '<'))}}"
  tags: ['ant']

- block:
  - name: download ant
    get_url:
      url: "http://archive.apache.org/dist/ant/binaries/apache-ant-{{ ant_version }}-bin.tar.gz"
      dest: "/tmp/apache-ant-{{ ant_version }}-bin.tar.gz"
      mode: 0644
    when: install_ant
    tags: ['ant']

  - name: create versions directory
    file:
      path: "{{ant_versions_dir}}"
      state: directory
      mode: 0755
    when: install_ant
    tags: ['ant']

  - name: extract archive with version {{ant_version}} to {{ant_versions_dir}}
    unarchive:
      copy: False
      src: "/tmp/apache-ant-{{ ant_version }}-bin.tar.gz"
      dest: "{{ant_versions_dir}}"
      creates: "{{ant_versions_dir}}/apache-ant-{{ ant_version }}"
    when: install_ant
    tags: ['ant']

  - name: point {{ant_home}} to the currently installed version
    file:
      path: "{{ant_home}}"
      src: "{{ant_versions_dir}}/apache-ant-{{ ant_version }}"
      state: link
      force: True
    when: install_ant
    tags: ['ant']
  always:
  - name: delete downloaded files
    file:
      state: absent
      path: "/tmp/apache-ant-{{ ant_version }}-bin.tar.gz"
    when: install_ant
    tags: ['ant']
