---
# add repel repository
- name: Add epel repository
  yum_repository:
    name: epel
    description: add epel repository
    baseurl: https://download.fedoraproject.org/pub/epel/{{release_version}}/{{base_arch}}/
- name: download and set repel GPG key
  rpm_key:
    state: present
    key: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{release_version}}
