---
- name: check which version is installed
  shell: "ls -1v {{ant_home}}/lib/commons-codec-*.jar | tail -1 | gawk 'match($0,/commons-codec-(.+)\\.jar/, group) {print group[1]}'"
  changed_when: false
  failed_when: false
  check_mode: no
  register: current_version
  tags: ['commons-codec']

- name: check if the new version should be installed or not
  set_fact:
    install_common_codec: "{{ (current_version.rc > 0) or (current_version.stderr_lines | length > 0) or (current_version.stdout | version_compare(commons_codec_version, '<'))}}"
  tags: ['commons-codec']

- block:
  - name: download
    get_url:
      url: "http://archive.apache.org/dist/commons/codec/binaries/commons-codec-{{commons_codec_version}}-bin.tar.gz"
      dest: "/tmp/commons-codec-{{commons_codec_version}}-bin.tar.gz"
    when: install_common_codec
    tags: ['commons-codec']

  - name: extract commons-codec-{{commons_codec_version}}.jar to {{ant_home}}/lib
    unarchive: 
      copy: False
      src: "/tmp/commons-codec-{{commons_codec_version}}-bin.tar.gz"
      dest: "{{ant_home}}/lib"
      extra_opts:
        - "--strip-components=1"
        - "commons-codec-{{commons_codec_version}}/commons-codec-{{commons_codec_version}}.jar"
    when: install_common_codec
    tags: ['commons-codec']
    
  always:
  - name: Delete commons-codex downloaded files
    file:
      state: absent
      path: "/tmp/commons-codec-{{commons_codec_version}}-bin.tar.gz"
    when: install_common_codec
    tags: ['commons-codec']